# Generated by Django 4.1 on 2022-08-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_location_alter_ad_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="author",
            new_name="author_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="location_id",
        ),
    ]
