# Generated by Django 4.1 on 2022-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_rename_location_user_locations_alter_ad_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
